# Generated by Django 4.0.3 on 2023-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_adi', models.CharField(max_length=100)),
                ('yonetmen', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('resim', models.CharField(max_length=120)),
                ('anasayfa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('resim', models.CharField(max_length=120)),
            ],
        ),
    ]
